Add dependent patch missing handling
I did this so that the tool could educate/remind the user that neglected
to get a dependent patch into origin/master before either requesting
review or trying to push a patch that depends on another missing patch.

diff --git a/git-ps b/git-ps
--- a/git-ps
+++ b/git-ps
@@ -14,6 +14,10 @@ list_patch_stack() {
   git log --pretty='format:%C(auto)%h %s' ${remote_base}..${base_branch}
 }
 
+list_patch_stack_up_to() {
+  git log --pretty='format:%C(auto)%h %s' ${remote_base}..$1~
+}
+
 print_ps_rr_usage() {
   echo "Usage: git rr <branch_name> <sha>"
   echo "Usage: git rr -i|--interactive <branch_name>"
@@ -101,13 +105,11 @@ checkout_branch_with_name() {
 
 cherry_pick() {
   # cherry pick the commit
-  git cherry-pick $1
+  git cherry-pick $1 > /dev/null 2>&1
   if [ $? -ne 0 ]; then
-    echo "warn: Failed to cherry-pick $1. This is likely due to a conflict."
-    echo "You should probably complete the cherry-pick, and then do the following:"
-    echo "  - push updated branch up to remote using - git push -f ${remote} ${brach_name}:${branch_name}"
-    echo "  - checkout the branch you were on originally using - git checkout ${original_branch_name}"
-    exit 8
+    echo -n "failed"
+  else
+    echo -n "succeeded"
   fi
 }
 
@@ -118,6 +120,15 @@ push_branch_up() {
     echo "warn: Failed to push $1 up to ${remote}"
     echo "You should figure out why the push failed and correct the issue and push the branch up to the remote."
     exit 9
+  fi
+}
+
+cherry_pick_abort() {
+  git cherry-pick --abort
+  if [ $? -ne 0 ]; then
+    echo "error: Failed to abort cherry pick"
+    echo "I don't believe this should every happen. If it does we should really understand why and handle it better."
+    exit 30
   fi
 }
 
@@ -158,7 +169,20 @@ request_review() {
 
   create_branch_on_remote_base_with_name ${branch_name}
   checkout_branch_with_name ${branch_name}
-  cherry_pick ${commit_sha}
+  cherry_pick_res=$(cherry_pick ${commit_sha})
+  if [ "${cherry_pick_res}" = "failed" ]; then
+    echo "Looks like you are trying to request review of (${commit_sha}), a patch that is dependent on another patch that is NOT currently in ${remote_base}. Dependent patches MUST be in ${remote_base} before requesting review for patches that depend on them."
+    echo ""
+
+    list_patch_stack_up_to ${commit_sha}
+
+    echo ""
+    echo "Please consider whether the patch should actually be dependent or if it should rather be altered such that it is independent and can be reviewed independently."
+
+    cherry_pick_abort
+    checkout_branch_with_name ${base_branch}
+  fi
+  
   push_branch_up ${branch_name}
   checkout_branch_with_name ${original_branch_name}
 }
@@ -174,7 +198,6 @@ push_branch_to_mainline() {
     exit 21
   fi
 }
-
 
 push() {
   fetch_upstream
@@ -213,7 +236,20 @@ push() {
 
   create_branch_on_remote_base_with_name ${branch_name}
   checkout_branch_with_name ${branch_name}
-  cherry_pick ${commit_sha}
+  cherry_pick_res=$(cherry_pick ${commit_sha})
+  if [ "${cherry_pick_res}" = "failed" ]; then
+    echo "Looks like you are trying to push (${commit_sha}), a patch that is dependent on another patch that is NOT currently in ${remote_base}.  Dependent patches MUST be in ${remote_base} before pushing patches that depend on them." 
+    echo ""
+    echo "The dependent patch is one or more of the following:"
+
+    list_patch_stack_up_to ${commit_sha}
+
+    echo ""
+    echo "Please consider whether the patch should actually be dependent or if it should rather be altered such that it is independent and can be reviewed independently and pushed independently."
+
+    cherry_pick_abort
+    checkout_branch_with_name ${base_branch}
+  fi
 
   push_branch_to_mainline ${branch_name}
 
