Add push functionality
I did this so that users would be able to easily select a commit and
have it pushed up to the remote mainline. I also extracted functionality
into functions so that things are bettered factored.

diff --git a/git-ps b/git-ps
--- a/git-ps
+++ b/git-ps
@@ -19,6 +19,107 @@ print_ps_rr_usage() {
   echo "Usage: git rr -i|--interactive <branch_name>"
 }
 
+fetch_upstream() {
+  git fetch --quiet origin master
+  if [ $? -ne 0 ]; then
+    echo "fatal: Failed to fetch latest state from ${remote} ${base_branch}"
+    exit 20
+  fi
+}
+
+validate_skim_is_available() {
+  command -v sk >/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    echo "fatal: interactive mode depends on the 'skim' fuzzy finder but it in't in the path'"
+    echo "If you haven't installed you can easily do so via: brew install sk"
+    exit 2
+  fi
+}
+
+select_commit_with_skim() {
+  selected_log_entry=$(git log --pretty='format:%C(auto)%h %s' ${remote_base}..${base_branch} | sk)
+  if [ "${selected_log_entry}" = "" ]; then
+    echo "fatal: You neglected to select a commit to request review for."
+    echo "We can't request a review if you don't tell us what you want reviewed silly."
+    exit 3
+  fi
+  echo "${selected_log_entry}"
+}
+
+parse_sha_from_log_entry() {
+  commit_sha=$(echo $1 | awk -F' ' '{print $1}')
+  echo "${commit_sha}"
+}
+
+validate_sha_exists() {
+  # Make sure that a commit with the provided sha exists.
+  res=$(git cat-file -t $1 2> /dev/null)
+  if [ "${res}" != "commit" ]; then
+    echo "fatal: Not a valid commit name ${commit_sha}"
+    exit 4
+  fi
+}
+
+validate_no_uncommited_changes() {
+  # Make sure there aren't any local un-committed changes as this must
+  # change branches to be able to cherry-pick the specified commit into the
+  # branch.
+  git diff-index --quiet HEAD
+  if [ $? -ne 0 ]; then
+    echo "fatal: Uncommitted changes are present."
+    echo "Please commit or stash any uncommitted changes before running this command."
+    exit 5
+  fi
+}
+
+get_checked_out_branch() {
+  # Get currently checked out branch name
+  original_branch_name=$(git rev-parse --abbrev-ref HEAD)
+  echo "$original_branch_name"
+}
+
+create_branch_on_remote_base_with_name() {
+  # Creates the non-tracking branch named ${branch_name} based on
+  # ${remote_branch} when branch doesn't already exist. When the branch does
+  # already exist simply reset the branch to start at ${remote_base}, effectively
+  # dropping any commits it previously had if any.
+  git branch -f -q --no-track $1 ${remote_base}
+  if [ $? -ne 0 ]; then
+    echo "fatal: Failed to create/reset branch $1. No worries you are still in a decent state."
+    exit 6
+  fi
+}
+
+checkout_branch_with_name() {
+  git checkout -q $1
+  if [ $? -ne 0 ]; then
+    echo "fatal: Failed to checkout $1."
+    exit 7
+  fi
+}
+
+cherry_pick() {
+  # cherry pick the commit
+  git cherry-pick $1
+  if [ $? -ne 0 ]; then
+    echo "warn: Failed to cherry-pick $1. This is likely due to a conflict."
+    echo "You should probably complete the cherry-pick, and then do the following:"
+    echo "  - push updated branch up to remote using - git push -f ${remote} ${brach_name}:${branch_name}"
+    echo "  - checkout the branch you were on originally using - git checkout ${original_branch_name}"
+    exit 8
+  fi
+}
+
+push_branch_up() {
+  # force push up to the remote
+  git push -f -q ${remote} $1:$1
+  if [ $? -ne 0 ]; then
+    echo "warn: Failed to push $1 up to ${remote}"
+    echo "You should figure out why the push failed and correct the issue and push the branch up to the remote."
+    exit 9
+  fi
+}
+
 request_review() {
   # Make sure right number of arguments were passed to the command and validate
   # the values of those arguments as best as we can.
@@ -37,21 +138,10 @@ request_review() {
   fi
 
   if [ $interactive -eq 1 ]; then
-    command -v sk >/dev/null 2>&1
-    if [ $? -ne 0 ]; then
-      echo "fatal: interactive mode depends on the 'skim' fuzzy finder but it in't in the path'"
-      echo "If you haven't installed you can easily do so via: brew install sk"
-      exit 2
-    fi
+    validate_skim_is_available
 
-    selected_log_entry=$(git log --pretty='format:%C(auto)%h %s' ${remote_base}..${base_branch} | sk)
-    if [ "${selected_log_entry}" = "" ]; then
-      echo "fatal: You neglected to select a commit to request review for."
-      echo "We can't request a review if you don't tell us what you want reviewed silly."
-      exit 3
-    fi
-
-    commit_sha=$(echo ${selected_log_entry} | awk -F' ' '{print $1}')
+    selected_log_entry=$( select_commit_with_skim )
+    commit_sha=$( parse_sha_from_log_entry $selected_log_entry )
     branch_name=$2
   else
     branch_name=$1
@@ -60,77 +150,73 @@ request_review() {
 
   ## Input Validations
 
-  # Make sure that a commit with the provided sha exists.
-  res=$(git cat-file -t ${commit_sha} 2> /dev/null)
-  if [ "${res}" != "commit" ]; then
-    echo "fatal: Not a valid commit name ${commit_sha}"
-    exit 4
-  fi
+  validate_sha_exists $commit_sha
+  validate_no_uncommited_changes
 
-  # Make sure there aren't any local un-committed changes as this must
-  # change branches to be able to cherry-pick the specified commit into the
-  # branch.
-  git diff-index --quiet HEAD
-  if [ $? -ne 0 ]; then
-    echo "fatal: Uncommitted changes are present."
-    echo "Please commit or stash any uncommitted changes before running this command."
-    exit 5
-  fi
+  original_branch_name=$( get_checked_out_branch )
 
-  # Get currently checked out branch name
-  original_branch_name=$(git rev-parse --abbrev-ref HEAD)
-
-  # Creates the non-tracking branch named ${branch_name} based on
-  # ${remote_branch} when branch doesn't already exist. When the branch does
-  # already exist simply reset the branch to start at ${remote_base}, effectively
-  # dropping any commits it previously had if any.
-  git branch -f -q --no-track ${branch_name} ${remote_base}
-  if [ $? -ne 0 ]; then
-    echo "fatal: Failed to create/reset branch ${branch_name}. No worries you are still in a decent state."
-    exit 6
-  fi
-
-  # checkout the branch
-  git checkout -q ${branch_name}
-  if [ $? -ne 0 ]; then
-    echo "fatal: Failed to checkout ${branch_name}."
-    exit 7
-  fi
-
-  # cherry pick the commit
-  git cherry-pick ${commit_sha}
-  if [ $? -ne 0 ]; then
-    echo "warn: Failed to cherry-pick ${commit_sha} into ${branch_name}. This is likely due to a conflict."
-    echo "You should probably complete the cherry-pick, and then do the following:"
-    echo "  - push updated branch up to remote using - git push -f ${remote} ${brach_name}:${branch_name}"
-    echo "  - checkout the branch you were on originally using - git checkout ${original_branch_name}"
-    exit 8
-  fi
-
-  # force push up to the remote
-  git push -f -q ${remote} ${branch_name}:${branch_name}
-  if [ $? -ne 0 ]; then
-    echo "warn: Failed to push ${branch_name} up to ${remote}"
-    echo "You should figure out why the push failed and correct the issue and push the branch up to the remote."
-    exit 9
-  fi
-
-  # check out the original branch we were on
-  git checkout -q ${original_branch_name}
-  if [ $? -ne 0 ]; then
-    echo "warn: Failed to checkout ${original_branch_name}"
-    echo "You should probably figure out why the this failure occured, as it is unexpected."
-    echo "This command has nothing left to do, so don't stress too much."
-    exit 10
-  fi
+  create_branch_on_remote_base_with_name ${branch_name}
+  checkout_branch_with_name ${branch_name}
+  cherry_pick ${commit_sha}
+  push_branch_up ${branch_name}
+  checkout_branch_with_name ${original_branch_name}
 }
 
 rebase() {
   git rebase -i --onto ${remote_base} ${remote_base} ${base_branch}
 }
 
+push_branch_to_mainline() {
+  git push ${remote} $1:${base_branch}
+  if [ $? -ne 0 ]; then
+    echo "fatal: failed to push $1 up to ${remote_base}"
+    exit 21
+  fi
+}
+
+
 push() {
-  echo "push a patch to mainline"
+  fetch_upstream
+
+  # Make sure right number of arguments were passed to the command and validate
+  # the values of those arguments as best as we can.
+  if [ "$#" -ne 2 ]; then
+    echo "Wrong number of arguments"
+    print_ps_rr_usage
+    exit 1
+  fi
+
+  # Options Parsing
+
+  if [ "$1" = "-i" ] || [ "$1" = "--interactive" ]; then
+    interactive=1
+  else
+    interactive=0
+  fi
+
+  if [ $interactive -eq 1 ]; then
+    validate_skim_is_available
+
+    selected_log_entry=$( select_commit_with_skim )
+    commit_sha=$( parse_sha_from_log_entry $selected_log_entry )
+    branch_name=$2
+  else
+    branch_name=$1
+    commit_sha=$2
+  fi
+
+  validate_sha_exists $commit_sha
+  validate_no_uncommited_changes
+
+  original_branch_name=$( get_checked_out_branch )
+
+  create_branch_on_remote_base_with_name ${branch_name}
+  checkout_branch_with_name ${branch_name}
+  cherry_pick ${commit_sha}
+
+  push_branch_to_mainline ${branch_name}
+
+  # delete the local temp branch
 }
 
 validate_min_num_args_met() {
@@ -142,14 +228,9 @@ validate_min_num_args_met() {
   fi
 }
 
-parse_subcommand() {
-  rv=$1
-  shift
-  echo "${rv}"
-}
-
 validate_min_num_args_met $@
-subcommand=$( parse_subcommand $@ )
+subcommand=$1
+shift
 
 if [ "$subcommand" = "ls" ]; then
   list_patch_stack
